name: SimplerBroadcaster
version: 1.0.0
main: DerCommander610\Broadcast\Main
api: [5.0.0, 5.12.0]

commands:
  broadcast:
    description: "Send every Player on your Server a Message"
    permission: broadcast.cmd
permissions:
   broadcast.cmd:
      default: op 
